### PR TITLE
Add support to AArch64 machine

### PR DESCRIPTION
**Pull request by cascades-sjtu**

### CODE REVIEW

**Comment by Enkelmann** [comment]
Thank you for your PR, providing an AArch64-based Docker image for usage with newer Macs sounds like a great idea! Before I merge this I have some questions about build and usage instructions:

Did you build the `ghidra_headless_base:aarch64` image yourself? If yes, did you need to change anything in its Dockerfile for building it? I want to provide complete usage instructions for the new image and since the `ghidra_headless_base` image on Dockerhub should also be amd64-based, I am wary of missing some important step in its build process.

I am not really concerned about anything going wrong when compiling everything for AArch64, so running the complete test suite is not a high priority for me right now. But ultimately we want to add the AArch64-based images to our CI and also deploy them on Dockerhub, so that users do not have to build them themselves. I will have to figure out how to do that myself in time, so you don't have to worry about that. If you want to test that the basic functionality works as intended, you can just compile some of the test cases in `test/artificial_samples` for your native platform and run the cwe_checker on them.

**Comment by cascades-sjtu** [comment]
To answer your first question: I've build a AArch64 version of ghidra_headless_base by adding `platform` to openjdk in its [Dockerfile](https://github.com/fkie-cad/docker_ghidra_headless_base/blob/master/Dockerfile). I've push it to [docker hub](https://hub.docker.com/r/cascadessjtu/ghidra_headless_base), but I forget to change the image name in my PR, sorry for my silly mistake 😷

**Comment by cascades-sjtu** [comment]
As for the complete test suite, I will try this myself following your instructions. May you provide me the original cwe_checker's preformance or batch test scripts on `test/artificial_samples`, so that I can make a comparison between amd64 and AArch64?
Actually, I'm a freshmen in binary security. I've started learning cwe_checker(It's really a good tool!), and I hope to make more contributions to this project, thanks for your kindness and help~

**Comment by Enkelmann** [comment]
Could you open a pull request for your version of `ghidra_headless_base` in https://github.com/fkie-cad/docker_ghidra_headless_base ? This way we could provide both images ourselves and also update them both whenever necessary (e.g. for newer Ghidra versions) without needing to bother you.

**Comment by cascades-sjtu** [comment]
> Could you open a pull request for your version of `ghidra_headless_base` in https://github.com/fkie-cad/docker_ghidra_headless_base ? This way we could provide both images ourselves and also update them both whenever necessary (e.g. for newer Ghidra versions) without needing to bother you.

OK, I'll do it now

**Comment by Enkelmann** [comment]
Since @jstucke managed to push a multi-architecture-version of the `ghidra_headless_base` image to Dockerhub I will try to do the same with the cwe_checker images that get automatically generated by our CI. If that works we would not need a second Dockerfile anymore! But if it fails I will merge your PR, so that people can at least build an ARM-based image locally. I will keep you updated about my progress, especially since I might need your help to test whether the end result works as intended.

**Comment by Enkelmann** [comment]
Yeah, apparently the cross compiling with `docker buildx` needs some nontrivial setup steps before it actually works. But fortunately other people already figured out that part for us and thus it was surprisingly simple to add multi-architecture builds to our CI pipeline! You can find the result in PR #322. Since I cannot check on my PC whether the `linux/arm64` based images actually work as intended, I pushed a test build to Dockerhub as `fkiecad/cwe_checker:multiarch`. Could you verify for us that this image works as intended on your MacBookPro, i.e. is as fast as your native builds?

**Comment by cascades-sjtu** [comment]
> fkiecad/cwe_checker:multiarch

**Comment by Enkelmann** [comment]
Thank you for your help in all of this! :-) PR #322 is now merged, we are now deploying multi-architecture builds of the cwe_checker Docker image to Dockerhub!

Closing this PR, since the extra Dockerfile is no longer necessary thanks to `docker buildx`.

**Pull request closed without merging**
